#!/bin/bash
docker_name="ghost_eye"
echo
echo "This will remove $docker_name container, image and build $docker_name"
read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
 docker container stop $docker_name
 docker container stop $docker_name
 docker container rm $docker_name
 docker image rm $docker_name
 docker build -t $docker_name .
fi
