#!/bin/bash
# Removes lines in python code that does not work
# orig ghost_eye.py -> wget https://raw.githubusercontent.com/BullsEye0/ghost_eye/master/ghost_eye.py
ghost_eye_location="ghost_eye.py"

echo Fixing python code for not working menu option
sed -i "s/os\.system(\"reset\")/print\(\"EtherApe – Does not work in docker enviroment\"\)/g" $ghost_eye_location
sed -i "/\"sudo etherape; exec bash/d" $ghost_eye_location

#sed -i "s/os\.system(\"reset\")/print(\"033\[1;91mEtherApe – Does not work in docker enviroment\\033\[1;m \")/g" $ghost_eye_location
