#!/bin/bash
docker_name="ghost_eye"
echo "Starting $docker_name..."
docker container stop $docker_name
[ ! "$(docker ps -a | grep $docker_name)" ] && docker run -ti --name $docker_name $docker_name
[ "$(docker ps -a | grep $docker_name)" ] && docker run -ti $docker_name
